### ISSUE TITLE
Datenbank ?

### ISSUE THREAD

**Issue by panigrc** [derrabus/phpbb-workshop#1]
Ist es moeglich die Datenbank als .sql Datei herauf zu laden ?

**Comment by derrabus** [comment]
Als Workshop-Teilnehmer solltest du die Datenbank, die wir im Workshop verwendet haben, auf deiner VM finden.

Eine leere Datenbank findest du hier: https://github.com/derrabus/phpbb-workshop/blob/00-start/docs/phpBB.schema

**Comment by panigrc** [comment]
Danke. Habe die docs nicht gesehen.
